### ISSUE TITLE
Is this normal behaviour?

### ISSUE THREAD

**Issue by dmike3** [RandomNinjaAtk/docker-radarr-extended#11]
So I got everything installed and running.

However, the logs for MovieExtras shows the following.

MovieExtras :: Cookies File Not Found!

**Comment by RandomNinjaAtk** [comment]
I need to add documentation about this, but its looking for a Cookies.txt file that can be located anywhere within the dockers /config folder.

Cookies.txt is used for yt-dlp for authing (age-restriction) purposes, you'll need to look up how to actually generate a Cookies.txt file, if you don't know how to already.

**Comment by dmike3** [comment]
Okay thanks. I pulled a cookies.txt file from youtube, but I would imagine there has to be some sort of expiration on this? What happens when it expires? Will everything stop working, or will it just continue to work as if I didn't have a cookies.txt file in the config directory?

**Comment by RandomNinjaAtk** [comment]
I don't know, I don't think I've ever had it expire...

**Comment by dmike3** [comment]
I spun up my AMTD and it ended up grabbing trailers and extras that the radarr-extended did not grab?

**Comment by RandomNinjaAtk** [comment]
There are certain categories of extras that are not included in this version of the script because there is no consensus to support all of the apps.

**Comment by dmike3** [comment]
So this script won’t grab all trailers and extras if what? The older one grabbed a ton and it’s setup with the Emby env.

**Comment by RandomNinjaAtk** [comment]
It should grab all extras matching your language in these 3 categories:
https://github.com/RandomNinjaAtk/docker-radarr-extended/blob/b294b99749600c164b1939a042b7c60e026f552c/root/scripts/MovieExtras.bash#L127-L132
If its not one of those, it does not grab it at this time...

**Comment by RandomNinjaAtk** [comment]
No response, closing....
