### ISSUE TITLE
Naming setting

### ISSUE THREAD

**Issue by memnos** [RandomNinjaAtk/docker-radarr-extended#13]
Hello, i don't know if it is a normal behavior or if it is radarr-extended problem or just radarr docker problem, but i have this situation.

I modified naming settings this way:
{Movie Title:it} ({Release Year})-{Quality Title}-{IMDb Id}-{Release Group}

But each time i update radarr-extended docker naming settings both for movie name and folder name are changed to default settings.

Is this normal? Can i do anything to change this behaviour?

**Comment by RandomNinjaAtk** [comment]
Disable auto config, which is updating those settings.

**Comment by memnos** [comment]
What does autoconfig do?
What does it change if i disable it?

**Comment by memnos** [comment]
So, if i disable autoconfig i loose all this? Or it is enough i run it the first time to have it configurated?

Settings -> Media Management
Movie Naming (based on best practices, trashguide)
File Management
File Permissions
Settings -> Metadata
Enables kodi, images + nfo)
Settings -> Connect
Adds MovieExtras.bash post processing script
Adds PlexNotify.bash post processing script

**Comment by RandomNinjaAtk** [comment]
If you disable it, it will just prevent any future changes to your settings automatically. You won't loose anything, you just won't have any automated updates to your settings if things are adjusted later.

**Comment by memnos** [comment]
Ok, so it is a good thing sometimes to update docker with autoconfig enabled?

**Comment by RandomNinjaAtk** [comment]
Probably not much is changing going forward because I'd like to say this is mostly feature complete at this point... Except for bugfixes, so you can most likely just leave it off without an issue.

**Comment by memnos** [comment]
tnx
