### ISSUE TITLE
Trailers and extra's not downloading

### ISSUE THREAD

**Issue by Shizly** [RandomNinjaAtk/docker-radarr-extended#20]
Trailers and extra's are not being downloaded. I tried it with multiple movies that all have en-us video content on tmdb.

[Pastebin of MovieExtras.txt log](https://pastebin.com/3iLhMsmd)

[Pastebin of AutoExtras.txt log](https://pastebin.com/2nC2geFR) (note: all logging is before I added LotR to Plex)

[Pastebin of Radarr log](https://pastebin.com/1mhbaQug)

[Pastebin of the Radarr-part of the docker-compose.yml](https://pastebin.com/d8rP1wcB)

Radarr seems to work fine. It search movies and let the downloader download the movies, movies that are finshed downloading get moved to the Plex db path, Plex imports them, etc. In the movie folder there are also an \trailers, \featurettes\ and \behind the scenes-folder created, but these stay empty. 

Any thoughts on if I made a mistake somewhere and I'm missing something? Or whether there is something else going on?

**Comment by RandomNinjaAtk** [comment]
If you haven't added a Cookies.txt, that may be your issue.

See this link: https://github.com/RandomNinjaAtk/docker-radarr-extended/issues/11#issuecomment-1247231888

**Comment by Shizly** [comment]
Ha, missed that one, but that didn't solve it. I've added it and it worked for the "Cookies File Not Found!" in the MoviesExtras logline, but the trailer and features downloads still keep failing.

Current logs after adding the cookie.txt:

[Pastebin of AutoExtras log](https://pastebin.com/P7JyrFi8)

[Pastebin of MovieExtras log](https://pastebin.com/BQn7Hh03)

[Pastebin of Radarr log](https://pastebin.com/dxkikCzJ)

**Comment by RandomNinjaAtk** [comment]
After the latest image builds, update to it, and see what your logs say then.... It should show more detailed log output, that might indicate what the issue is....

**Comment by Shizly** [comment]
That make's it a bit clearer.

From MoviesExtras log:

```
2022-10-16 16:46:57 :: MovieExtras :: Bullet Train :: 15 of 102 :: Featurette :: Lucky or Unlucky: Gunpoint (57zLgA_EIyc) :: Downloading...
ERROR: Fixed output name but more than one file to download: /data/movies/Bullet Train (2022)/featurettes/Lucky or Unlucky Gunpoint
2022-10-16 16:46:58 :: MovieExtras :: Bullet Train :: 15 of 102 :: Featurette :: Lucky or Unlucky: Gunpoint (57zLgA_EIyc) :: ERROR :: Download Failed
```

In the docker-compose.yml changing from "- extrasLanguages=en-US, nl-NL" to "- extrasLanguages=en-US" solved this. Not sure whether this was caused by the extra space between 'en-US, nl-NL' or because it was 2 languages. I haven't been able to test that just yet.

**Comment by RandomNinjaAtk** [comment]
You should be able to use both, but don't include spaces

**Comment by Shizly** [comment]
Yeah, it does seem to be the spaces. Always the little things. Thank you for looking into this!
