### ISSUE TITLE
settings for refreshing library and looking for missing extras/trailers

### ISSUE THREAD

**Issue by Kamikaze01git** [RandomNinjaAtk/docker-radarr-extended#23]
Hi (again)...

as the [WIKI](https://github.com/RandomNinjaAtk/docker-radarr-extended/wiki/MovieExtras.bash) for the MovieExtras.bash says, it _only runs as a post processing script during Radarr download imports._

But in RADARR itself the settings for the script are set
"on import"
"on upgrade"
"on rename"
"on Movie File Delete" and
"on Movie File Delete for Upgrade"

What can i do to download alle possible extras, if my file is already correctly named?
How can i start the script manually for my whole library and look for missing extras in every singe movie folder?

As mentioned for the AutoExtras.bash [WIKI](https://github.com/RandomNinjaAtk/docker-radarr-extended/wiki/AutoExtras.bash) _when "enableExtras" is enabled, this script will run in the background, processing all movies in Radarr. It basically loops the Radarr movie list and process them using the MovieExtras.bash script._

Soooo... are my settings right?
If i refresh my library, nothing happend and no new extras (trailers) are downloaded.
But if i name a movie wrong and hit the rename button in RADARR, than a trailer is downloaded...

i dont need the trailer named as "movie-trailer"...
and i want to download all possible extras

MoviesExtra.bash
```
#extrasLanguages=de-DE
#extrasType=all
#extrasOfficialOnly=false
#extrasKodiCompatibility=false
#extrasSingle=false
#enableExtras=true
```

by the way: what would be the other options for "extrasType" than "all"....?

**Comment by RandomNinjaAtk** [comment]
Read the logs, AutoExtras runs when Extras are enabled. So you just have to wait...

**Comment by Kamikaze01git** [comment]
thx for clearing this !

i have allready read carefully the readme and the wiki.
my db is quite big and i have to wait for it to be completely imported.
i will ask general questions in the discussion section next time 👍
