### ISSUE TITLE
SMA missing

### ISSUE THREAD

**Issue by Protektor-Desura** [RandomNinjaAtk/docker-radarr-extended#24]
Is SMA scripts no longer supported in this Radarr version? I have been relying on them to standardize my videos.

**Comment by RandomNinjaAtk** [comment]
SMA is installed, just no script is provided to use it. The extras features uses SMA.

**Comment by RandomNinjaAtk** [comment]
Example usage: https://github.com/RandomNinjaAtk/docker-radarr-extended/blob/410a334ef89ddeb5d31544f2095cafe876b33946/root/scripts/MovieExtras.bash#L201

**Comment by albanyeye** [comment]
Hi 
I’m sorry I don’t understand how to use this feature instead of the previous SMA feature.
I see sma.bash in the scripts folder.
I have a custom autoProcess.ini file. Where do I place this file?
Thanks

**Comment by RandomNinjaAtk** [comment]
@albanyeye 

If you add SMA.bash as a custom script connection, you'll need to update the `/config/extended/configs/sma.ini` file for any changes you want to make from the default. Something to keep in mind though, HW acceleration is not supported.
