### ISSUE TITLE
Standard Movie Format Not Saving

### ISSUE THREAD

**Issue by dannymichel** [RandomNinjaAtk/docker-radarr-extended#27]
Settings for ``Media Management > Standard Movie Format`` aren't saving ``{Movie CleanTitle} {(Release Year)}``. Every time the docker container updated, it goes back to the default.

This only happens with your version of radarr and not the official version
```
    ports:
      - '7878:7878'
    volumes:
      - '/data/radarr:/config'
      - '/media:/media'
```
```
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
```
```
➜  ~ ls -lah /data/radarr
drwxr-xr-x   12 aivit aivit 4.0K Nov  7 20:14 .
drwxr-xr-x   35 aivit aivit 4.0K Nov  7 09:10 ..
drwxr-xr-x    2 aivit aivit 4.0K Oct 26 12:41 asp
drwxr-xr-x    4 aivit aivit 4.0K Feb 24  2020 Backups
drwxrwxr-x    2 aivit aivit 4.0K May 24 02:00 bak
drwxrwxr-x    3 aivit aivit 4.0K May 23 18:30 bak.orig
-rw-rw-r--    1 aivit aivit  553 Nov  7 19:51 config.xml
drwxr-xr-x    2 aivit aivit 4.0K Jun 26  2021 custom-cont-init.d.xhrjh38q
drwxr-xr-x    2 aivit aivit 4.0K Jun 26  2021 custom-services.d.xhrjh38q
drwxrwxrwx    6 aivit aivit 4.0K Sep 24 05:06 extended
drwxr-xr-x    2 aivit aivit 4.0K Nov  7 19:46 logs
-rw-r--r--    1 aivit aivit 6.9M Nov  7 20:01 logs.db
drwxr-xr-x 2063 aivit aivit  36K Nov  6 03:00 MediaCover
-rwxr-xr-x    1 aivit aivit    4 Feb  8  2020 nzbdrone.pid
-rw-rw-r--    1 aivit aivit  44M Nov  7 20:13 radarr.db
-rw-rw-r--    1 aivit aivit  32K Nov  7 20:28 radarr.db-shm
-rw-rw-r--    1 aivit aivit 516K Nov  7 20:28 radarr.db-wal
-rw-r--r--    1 aivit aivit    3 Nov  7 19:51 radarr.pid
drwxr-xr-x    2 aivit aivit 4.0K Feb  8  2020 UpdateLogs
```
logs:
https://gist.github.com/dannymichel/4adba899f8147d99126e6e02e7ed0d06

https://gist.github.com/dannymichel/a0c256ab2d6b852dec69dc4dd797222d

**Comment by RandomNinjaAtk** [comment]
Disable "enableAutoConfig" by setting it to false.

More details here: https://github.com/RandomNinjaAtk/docker-radarr-extended#parameters
And here: https://github.com/RandomNinjaAtk/docker-radarr-extended/wiki/AutoConfig.bash

**Comment by RandomNinjaAtk** [comment]
The solution is to disable autoconfig script, however, recent changes should also prevent overwrites after every container restart. I'm closing this issue because everything should be resolved with proper configuration or the latest enhancements after you update. If your still having an issue after fully updating and after you've corrected your miss configuration, open a new issue so it can be addressed.
