### ISSUE TITLE
Feature request: Manually run download of trailers & extras

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/docker-radarr-extended#28]
This is a really excellent script.

Unfortunately, trailers are only downloaded upon import. Sometimes trailers will only become available later because I keep adding links to TMDB.

Is there any way to manually run the script to download trailers&extras for all movies in my Radarr library? Also, is there a list of movies that don't have a trailer? I can then manually add links to it.

Same feature request for sonarr-extended ;-)

Thanks for considering.

**Comment by RandomNinjaAtk** [comment]
It already does this on a schedule using the AutoExtras.bash script.

https://github.com/RandomNinjaAtk/docker-radarr-extended/blob/main/root/scripts/AutoExtras.bash
