### ISSUE TITLE
More information is required

### ISSUE THREAD

**Issue by erkexzcx** [RandomNinjaAtk/docker-radarr-extended#3]
So I've came from [docker-amtd](https://github.com/RandomNinjaAtk/docker-amtd) project and since it got deprecated, a new project [docker-radarr-extended](https://github.com/RandomNinjaAtk/docker-radarr-extended) is suggested.

After reading through this project, I am still not able to get a wider image of what it does. Can you clarify is it a replacement (fork) of Radarr project and not a standalone companion app?

**Comment by RandomNinjaAtk** [comment]
It's linuxserver.io container (Radarr (develop) with additional scripts packaged in, so its not a true fork, no modifications were made to Radarr itself, radarr is updated normally when the linuxserver image is updated

AMTD was added into this container, along with some other scripts. This just sreamlines it by packaging it into the container itself.

**Comment by erkexzcx** [comment]
Ohhh, I've missed the chance to look into the Wiki. My bad. Can you add a note to `README.md` something like below, so it clarifies where to look for the info? :)

> Full documentation can be found in [Wiki](https://github.com/RandomNinjaAtk/docker-radarr-extended/wiki).

**Comment by RandomNinjaAtk** [comment]
That info wasn’t there when you first looked. This is still very early, but working well in my setup.

**Comment by RandomNinjaAtk** [comment]
I've updated the home page and wiki with more detail. I'm going to close this issue, but if you have further questions, please feel free to use the discussions for posting ideas, questions and etc....
