### ISSUE TITLE
Kodi Compatible Trailers Naming not working to specifications

### ISSUE THREAD

**Issue by bullwinkl** [RandomNinjaAtk/docker-radarr-extended#41]
When Kodi Compatible Trailers option is selected, trailers are being saved in the proper directory, but with the filename "movie-trailer.mkv".

These are not picked up by Kodi as local trailers.  For the locally downloaded trailer to be used in Kodi, it must be named the same as the movie file but have -trailer appended to the name with no spaces.

examples of current behavior and desired behavior are attached as screenshots.
![current behavior](https://user-images.githubusercontent.com/25514305/225719152-ad04dba1-ab0d-4fd0-a4fb-62c9e6ec449e.png)
![desiredbehavior](https://user-images.githubusercontent.com/25514305/225719170-d231c24d-1909-4859-b984-ba6ee1a3e434.png)

Official Kodi documentation for local trailers can be found at https://kodi.wiki/view/Trailers#Scan_Local

**Comment by RandomNinjaAtk** [comment]
Try the latest, it's untested but should do the job....

**Comment by bullwinkl** [comment]
Looks good!  Thanks!
