### ISSUE TITLE
No Extras are being downloaded

### ISSUE THREAD

**Issue by fromage9747** [RandomNinjaAtk/docker-radarr-extended#45]
I have not been able to get any extras to download.

I recall reading somewhere that this only happens on initial import of a library, so I have also removed my library and re-added it, but there are no extras downloaded other than the normal posters that Radarr downloads.

This is being tested on a small 3D movie library before making use of it in my main library.  There are 43 movies in this library. 

Can I be pointed in the right direction to troubleshoot this? 

Below are my env variables:

```
environment:
      - PUID=1000
      - PGID=1000
      - enableAutoConfig=true
      - enableRecyclarr=true
      - enableQueueCleaner=true
      - enableExtras=true
      - extrasType=all
      - extrasLanguages=en-US
      - extrasOfficialOnly=false
      - extrasSingle=false
      - extrasKodiCompatibility=true
      - plexUrl=http://192.168.1.4:32400
      - plexToken=REDACTED
```

The only thing that runs when looking at the logs is the Queue Cleaner.

However, when I removed all the items in my library I then saw it throwing errors for the "MovieExtras.bash" but once I added movies back to the library there were no longer any errors, but there was also no indication that "MovieExtras.bash" was running as well.

**Comment by fromage9747** [comment]
I changed the below to true to see if that would make a difference but there was no change:

```
      - extrasOfficialOnly=false
      - extrasSingle=false
```

**Comment by RandomNinjaAtk** [comment]
Have you checked for the log files?

You should have a log file for each script that is running.

**Comment by mtauberjr** [comment]
I think im having same issue. I dont see any logs. but I see the extended folder. not sure if they latest release is missing anything? 
![image](https://user-images.githubusercontent.com/284211/227745927-b556d364-aae9-4b6b-a33f-a407e7438b2c.png)

**Comment by RandomNinjaAtk** [comment]
In the web interface, go to system -> logs:
![image](https://user-images.githubusercontent.com/8386416/227748357-39827660-65a3-427b-8fa5-c6b8f0bd35a0.png)

**Comment by mtauberjr** [comment]
![Uploading 6096E350-D016-4F38-BE9E-BABF3168FF80.png…]()

**Comment by mtauberjr** [comment]
![E6AA2F51-41FD-4D13-AA30-E386DCDD4991](https://user-images.githubusercontent.com/284211/227750923-6e3ab982-ebce-4770-a483-6b39872259aa.png)

**Comment by mtauberjr** [comment]
![5B358EE7-B1A4-4BF5-9771-2CAD80EFD5B5](https://user-images.githubusercontent.com/284211/227750971-8feb54e8-c78d-465d-8911-3e8157aaba55.jpeg)

**Comment by fromage9747** [comment]
Thanks for this.  Checking the logs, it just states that nothing has been found

```
2023-03-21 13:12:56 :: MovieExtras :: 1.0.019 :: Blade Runner 2049 :: Searching for "en-US" extras...
2023-03-21 13:12:56 :: MovieExtras :: 1.0.019 :: Blade Runner 2049 :: None found...
2023-03-21 13:13:01 :: MovieExtras :: 1.0.019 :: Skipping plex notification, not needed....
2023-03-21 13:13:07 :: MovieExtras :: 1.0.019 :: Doctor Strange in the Multiverse of Madness :: Searching for "en-US" extras...
2023-03-21 13:13:07 :: MovieExtras :: 1.0.019 :: Doctor Strange in the Multiverse of Madness :: None found...
2023-03-21 13:13:12 :: MovieExtras :: 1.0.019 :: Skipping plex notification, not needed....
2023-03-21 13:13:19 :: MovieExtras :: 1.0.019 :: Dolittle :: Searching for "en-US" extras...
2023-03-21 13:13:19 :: MovieExtras :: 1.0.019 :: Dolittle :: None found...
```
I mean, surely there must be some content available for this?

Even low budget movies have trailers on YouTube.

**Comment by RandomNinjaAtk** [comment]
@fromage9747  

So it seems like you might be having a connectivity issue to the https://www.themoviedb.org/ website that is used to gather/pull the information.

It's not reproducible in my setup, so it could be something related to your network or docker configuration.

FYI: I've only ever tested this on X86-64 based platforms, specifically Unraid as the host... 

@mtauberjr

You could try executing the `AutoExtras.bash` bash script manually via the container cli using the following command: `bash /config/extended/scripts/AutoExtras.bash`

**Comment by fromage9747** [comment]
Aah... I suspect that these scripts don't take into account the Proxy defined by Radarr? 

Is there anyway that I can modify the scripts to run through my proxy?

**Comment by mtauberjr** [comment]
yeah I get file not found -- only file I have there is QueueCleaner.bash and folders

**Comment by mtauberjr** [comment]
Do I just copy the files from your github repo over and run it

**Comment by RandomNinjaAtk** [comment]
@fromage9747 

I don't know, these scripts at a basic level mostly just use curl, yt-dlp and other simple packages to do the work... You'd have to figure that out on your own...

Also based on your previous screenshot, something I just noticed. It appears you've really messed up your docker volumes, none of those directories should be there.... So your issue is likely caused by a miss configuration on your end....

@mtauberjr, post your docker config.... and

**Comment by mtauberjr** [comment]
yeah so I just ran your compose and worked fine. I think its something they way im running in saltbox wont work

**Comment by fromage9747** [comment]
@RandomNinjaAtk 

I just tested the query to https://api.themoviedb.org though postman running on the same network as the docker instance and I get results:

Postman get request: `https://api.themoviedb.org/3/movie/1924/videos?api_key=3b7751e3179f796565d88fdb2fcdf426&language=en-US`

Result:
```
{
    "id": 1924,
    "results": [
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "DC Super Scenes: Lois & Clark's Night Out",
            "key": "DRglvEvjcRg",
            "site": "YouTube",
            "size": 1080,
            "type": "Clip",
            "official": true,
            "published_at": "2022-10-11T19:00:05.000Z",
            "id": "634771e0d34eb3007e7c25b0"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Full Movie Preview",
            "key": "u_1UHAqSCd0",
            "site": "YouTube",
            "size": 1080,
            "type": "Clip",
            "official": true,
            "published_at": "2021-07-15T17:59:47.000Z",
            "id": "6209ef4c1cac8c006778632a"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Original Theatrical Trailer",
            "key": "cvrRJ5RzmaI",
            "site": "YouTube",
            "size": 360,
            "type": "Teaser",
            "official": true,
            "published_at": "2014-07-08T22:55:39.000Z",
            "id": "6383fec25e14e500862fd280"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Trailer",
            "key": "pUwxH4SM9Rg",
            "site": "YouTube",
            "size": 480,
            "type": "Trailer",
            "official": true,
            "published_at": "2013-07-26T02:35:52.000Z",
            "id": "64149fd2ede1b0287fdc6ed0"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | Deleted Scenes Part 2 | Warner Bros. Entertainment",
            "key": "fclHBV8hMIo",
            "site": "YouTube",
            "size": 360,
            "type": "Bloopers",
            "official": true,
            "published_at": "2012-11-19T18:54:47.000Z",
            "id": "6383fc76fb8346007c478f35"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | Deleted Scenes Part 1 | Warner Bros. Entertainment",
            "key": "e-2XXdzy2ZA",
            "site": "YouTube",
            "size": 360,
            "type": "Bloopers",
            "official": true,
            "published_at": "2012-11-19T18:54:47.000Z",
            "id": "6383fcf7229ae215b45ed878"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | Taking Flight:The Development of Superman | Warner Bros. Entertainment",
            "key": "g-tgqMbGulA",
            "site": "YouTube",
            "size": 480,
            "type": "Behind the Scenes",
            "official": true,
            "published_at": "2012-11-19T18:54:47.000Z",
            "id": "6383fd82fb83460087700fc3"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | The Magic Behind The Cape | Warner Bros. Entertainment",
            "key": "tNFAFBhh1cU",
            "site": "YouTube",
            "size": 480,
            "type": "Behind the Scenes",
            "official": true,
            "published_at": "2012-11-19T18:54:47.000Z",
            "id": "6383fe67fb834600cb2094e5"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | The Movie - Restored Scenes | Warner Bros. Entertainment",
            "key": "UmGpF_cj9oE",
            "site": "YouTube",
            "size": 360,
            "type": "Bloopers",
            "official": true,
            "published_at": "2012-11-19T18:54:46.000Z",
            "id": "6383fdde229ae2155c5370a2"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | Deleted Scenes Part 4 | Warner Bros. Entertainment",
            "key": "NdARRLz7tbw",
            "site": "YouTube",
            "size": 360,
            "type": "Bloopers",
            "official": true,
            "published_at": "2012-11-19T18:51:43.000Z",
            "id": "6383fc68b3316b007f3c2191"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | Making Superman: Filming The Legend | Warner Bros. Entertainment",
            "key": "5jmuhcosiis",
            "site": "YouTube",
            "size": 480,
            "type": "Behind the Scenes",
            "official": true,
            "published_at": "2012-11-19T18:51:43.000Z",
            "id": "6383fd2cbf09d1007b057ecf"
        },
        {
            "iso_639_1": "en",
            "iso_3166_1": "US",
            "name": "Superman: The Movie | Deleted Scenes Part 3 | Warner Bros. Entertainment",
            "key": "MaQ10_EUQ8E",
            "site": "YouTube",
            "size": 360,
            "type": "Bloopers",
            "official": true,
            "published_at": "2012-11-19T18:51:43.000Z",
            "id": "6383fe315b4fed00d166683f"
        }
    ]
}
```
If I run: `bash /config/extended/scripts/AutoExtras.bash` through the docker bash cli I get exactly the same results as before. `None found...`

**Comment by RandomNinjaAtk** [comment]
You're welcome to look through the code, but the issue isn't reproducible on my end, which means it's something unique to your environment.

Since I cannot reproduce the issue, there is nothing for me to review or fix.

**Comment by fromage9747** [comment]
@RandomNinjaAtk All good. Using the proxy on the curl had to be formatted differently.

If you are interested.  You could add this as an environment variable
for example:
USE_PROXY=true
PROXY_URL=http://xxx.xxx.xxx.xxx
PROXY_PORT=8080
PROXY_USERNAME=username
PROXY_PASSWORD=password

`tmdbVideosListData=$(curl -x PROXY_URL:PROXY_PORT --proxy-user PROXY_USERNAME:PROXY_PASSWORD-s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')`

Working like a charm, downloading the extras. ✌
