### ISSUE TITLE
Feature Request: Enable the use of a Proxy

### ISSUE THREAD

**Issue by fromage9747** [RandomNinjaAtk/docker-radarr-extended#46]
Currently, the Extended Radarr does not abide by the Proxy settings in Radarr.  Which is to be expected as its independent.

This is a feature request to allow the Extended scripts to be configured with a proxy. 

Docker ENV Variables
```
USE_PROXY=True
PROXY_URL=http://xxx.xxx.xxx.xxx/
PROXY_PORT=8080
PROXY_USERNAME=username
PROXY_PASSWORD=password
```

```
if [USE_PROXY = True] ; then
tmdbVideosListData=$(curl -x PROXY_URL:PROXY_PORT --proxy-user PROXY_USERNAME:PROXY_PASSWORD -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')
else 
tmdbVideosListData=$(curl -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')
fi
```

**Comment by fromage9747** [comment]
Thanks for this.  Doesn't the highlighted text override the if as it is outside the if, it will take precedence. 

![image](https://user-images.githubusercontent.com/23147783/227920143-9d3f3d8f-8b1b-4a9b-8646-7b72b57e3023.png)

Seems like it is, as I am getting "Not Found" as I did before.

**Comment by fromage9747** [comment]
@RandomNinjaAtk Yeah, once that extra line is commented out, it works as expected. At the moment it is overriding the proxy as it's outside the if

**Comment by fromage9747** [comment]
@RandomNinjaAtk Must I open another request for this amendment? 

Replace: 
```
do
    if [ "$useProxy" != "true" ] ; then
        tmdbVideosListData=$(curl -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')
    else
        tmdbVideosListData=$(curl -x $proxyUrl:$proxyPort --proxy-user $proxyUsername:$proxyPassword -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')
    fi
    tmdbVideosListData=$(curl -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')
    log "$itemTitle :: Searching for \"$filter\" extras..."
```
With
```
do
    if [ "$useProxy" != "true" ] ; then
        tmdbVideosListData=$(curl -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')
    else
        tmdbVideosListData=$(curl -x $proxyUrl:$proxyPort --proxy-user $proxyUsername:$proxyPassword -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')
    fi
    log "$itemTitle :: Searching for \"$filter\" extras..."
```

Removing the extra `tmdbVideosListData=$(curl -s "https://api.themoviedb.org/3/movie/$tmdbId/videos?api_key=$tmdbApiKey&language=$filter" | jq -r '.results[] | select(.site=="YouTube")')`

**Comment by RandomNinjaAtk** [comment]
This was fixed with the latest commits already, please review the commits/changes... https://github.com/RandomNinjaAtk/docker-radarr-extended/commit/9bf560a1bc69f3da85d31b05d4f83f49e825712b

**Comment by fromage9747** [comment]
Thanks man.  I wasn't aware. Will check it out
