### ISSUE TITLE
Permission for directories/files and saltbox inclusion and file naming

### ISSUE THREAD

**Issue by jscottdouglas** [RandomNinjaAtk/docker-radarr-extended#47]
1. can you please fix your permissions directory permissions should not be executable use 775 instead of 777, for bash scripts 775 or ideally 740 should be ok  also the trailer files being downloaded are being added as root and not the docker user. 

2. can you add in some env variable to set extended path log folder folder path, since you are using extended folder inside of radarr, this duplicates the log path. 
3. when attempting to use in saltbox ideally scripts in saltbox typically sit in /opt/scripts from a default standpoint, this can be overriden with inventory settings.  Not saying to do anything here but maybe it would be a good idea to add a variable to set the extended scripts folder path and drop the files there instead.
4. variable to set the trailer names in some sort of method.  I use emby but regardless ideally movie name + trailer/feature should be in the file name i've seen trailers added with the filename as "trailer.mkv" not making it easy to identify the name of a trailer so i'll need to go back and update the trailer names later on to be more name friendly.

**Comment by RandomNinjaAtk** [comment]
1. Appreciate your feedback but not making a change at this time unless a problem is identified with valid evidence to support a change.
2. No, the dual log paths are typically for different purposes. It's mainly a carry over from lidarr extended where it is mainly used. The majority of the extended script logs for all extended containers end up in /config/logs for ease of use and accesss.
3. Don't know what saltbox is, not making any unnecessary changes...
4. no, the file names come directly from themoviedb site, if you want to make changes, you should update the source.
