### ISSUE TITLE
log command issue

### ISSUE THREAD

**Issue by memnos** [RandomNinjaAtk/docker-radarr-extended#5]
Hello it seems my system Ubuntu 16.04 hasn't got "log" command.
I have this error:
13:02:32.2|Error|MovieExtras.bash|/config/extended/scripts/MovieExtras.bash: line 34: log: command not found

What should i do?
Tnx

**Comment by RandomNinjaAtk** [comment]
Hmm, that doesn't seem right, make sure you've fully updated to the latest image.

**Comment by RandomNinjaAtk** [comment]
I found what the problem is and fixed it in the latest commit.
