### ISSUE TITLE
Metadata question

### ISSUE THREAD

**Issue by quadcom** [RandomNinjaAtk/docker-radarr-extended#50]
I'm sorry if this is not the correct platform to ask a question.

I noticed that Radarr was grabbing images such as posters and fanart and storing them next to the media. But, it was not naming them according to the Kodi naming conventions.

I posted on the Radarr Discord and was told to come back here for support in this. 

https://discord.com/channels/264387956343570434/264388019585286144/1101149342313758742

**Comment by quadcom** [comment]
Sorry, one other thing that is related to Extended. Regarding trailers. 

The NFO file does list the trailer, but it lists the remote URL, not the local path of the downloaded trailer that the script grabs. 

Can this be changed so that the NFO has the correct local path to the trailer?

**Comment by RandomNinjaAtk** [comment]
I don't believe my scripts are writing the nfo, so that would be a radarr issue. But I'm just going by memory, feel free to review the scripts you are using here.
