### ISSUE TITLE
none of the sma scripting works

### ISSUE THREAD

**Issue by KRDucky** [RandomNinjaAtk/docker-radarr-extended#52]
I get only permissions errors and if I run the SMA.bash script manually inside the container, it says sma doesnt exist etc. I even copied the SMA files to the usr/local/sma folder and ran it and it gave errors about manual.py No module named 'converter'

**Comment by RandomNinjaAtk** [comment]
What platform are you on? If it's not amd64 that might be your issue.

**Comment by KRDucky** [comment]
AMD Ryzen 5600X so definitely AMD64

**Comment by RandomNinjaAtk** [comment]
Does the extras script work? That uses SMA for some of its processing features...

**Comment by KRDucky** [comment]
I can't even manually run the commands or script itself when exec -it in
the container

**Comment by RandomNinjaAtk** [comment]
Not being able to run it manually doesn't mean it isn't working. Please answer my question, additionally you'll need to likely provide script logs.

**Comment by RandomNinjaAtk** [comment]
Does the extras script work? 

If not, provide appropriate logs that demonstrates the failure.

**Comment by KRDucky** [comment]
I stopped even trying to use that stuff after 3 days of troubleshooting.

**Comment by RandomNinjaAtk** [comment]
Not sure how you expect to get something fixed by stating there's a problem and not providing any evidence of such problem with logs.

I'm closing this issue because it's not productive and no evidence has been provided vis requested logs.

**Comment by KRDucky** [comment]
I will send you the logs when I get around to it. But the docker container
does not work for the scripts

**Comment by KRDucky** [comment]
The SMA doesn't work but if you are referring to the auto config stuff ,
yes that works. But nothing on the SMA side. It said it was missing stuff
so I tried to install the missing stuff in the container
