### ISSUE TITLE
Possibly having a problem with PlexNotify

### ISSUE THREAD

**Issue by evilalmus** [RandomNinjaAtk/docker-radarr-extended#55]
Seems to be up and running, I just get the following error repeating in the log:

> 2023-06-16 12:21:40 :: PlexNotify :: 1.0.1 :: Plex Connection Established, version: 1.32.4.7195-7c8f9d3b6
> 2023-06-16 12:21:41 :: PlexNotify :: 1.0.1 :: Radarr :: ERROR: No Plex Library found containing path "/movies"
> 2023-06-16 12:21:41 :: PlexNotify :: 1.0.1 :: Radarr :: ERROR: Add "/movies" as a folder to a Plex Movie Library

'/movies' is the correct folder for my movies library and it is saying that the Plex Connection is established, so there may not be a problem. It would be nice to know what that log message is for though.

**Comment by RandomNinjaAtk** [comment]
You'd have to post your Plex movie  library configuration here. 

Typically if it doesn't work, it's because of a user misconfiguration.

**Comment by evilalmus** [comment]
> You'd have to post your Plex movie library configuration here.
> 
> Typically if it doesn't work, it's because of a user misconfiguration.

You want the movie library configuration from Plex? I'm not sure how to provide that other than screenshots. If there is something else I can provide I'm happy to do that.

![image](https://github.com/RandomNinjaAtk/docker-radarr-extended/assets/18252672/b8ad6217-7ad0-4a34-b1ee-539c0d5320a6)
![image](https://github.com/RandomNinjaAtk/docker-radarr-extended/assets/18252672/f5b2f2fb-bb2c-4845-819e-be6b36a8a04a)

**Comment by RandomNinjaAtk** [comment]
Hmm, that looks correct. Must be something else unique to your Plex library setup that is causing the issue. Which would require manual troubleshooting on your end but debugging the script. Not sure I can really help you unless it's broken in my own setup, but I don't believe it is.

**Comment by evilalmus** [comment]
Thank you, I started debugging the script and found the problem. 
In case anyone else runs into this. It's very important that the env variable `plexUrl` does not have a trailing slash.
`http://x.x.x.x:32400` works
`http://x.x.x.x:32400/` doesn't
