### ISSUE TITLE
Trailers aren't placed in subdirectory

### ISSUE THREAD

**Issue by tam1m** [RandomNinjaAtk/docker-radarr-extended#7]
Trailers aren't placed into the `/trailers` directory inside the movie folder.

With amtd and `USEFOLDERS=true` the structure was like this
```
/Movies/1917 (2019)/featurettes/The Incredible Story Behind 1917 Extra Access.mkv
/Movies/1917 (2019)/tailers/Official Trailer.mkv
/Movies/1917 (2019)/1917 (2019) [Bluray-2160p].mp4
...
```
With radarr-extended, it looks like this
```
/Movies/1917 (2019)/Trailer-trailer.mkv
/Movies/1917 (2019)/1917 (2019) [Bluray-2160p].mp4
```

Reading throuh the [code](https://github.com/RandomNinjaAtk/docker-radarr-extended/blob/22dcfe999efccbbf114bdbe14455d0fb96208f38/root/scripts/MovieExtras.bash#L151-L176), this seems to be a bug, rather than wanted behavior

**Comment by tam1m** [comment]
> so that is by design and not a bug...

Yeah, after reading the code for naming fully, I understand now.
So yes, I'm using the single trailer option.

These are my settings
```
      ## radar extended options
      - enableExtras=true
      - extrasType=all
      - extrasLanguages=en
      - extrasOfficialOnly=true
      - extrasSingle=true
      - extrasKodiCompatibility=false
  ```


> There also is no USEFOLDERS option, folders are used when multiple extras are.

Stil, I really likes the `USEFOLDERS` behavior. Any chance, you can add this back as an option?

**Comment by RandomNinjaAtk** [comment]
Should be resolved after the latest update builds and is available

**Comment by memnos** [comment]
I see all movie Trailers are called "movie-trailer.mkv"
Is there a setting to give them a different name? 
Or the name of the file downloaded or the name of the MOVIE_IN_THE_FOLDER-trailer.mkv?

**Comment by RandomNinjaAtk** [comment]
@memnos the latest update should resolve the file naming.

**Comment by memnos** [comment]
Tnx, nice to know, i'll try.
