### ISSUE TITLE
Trailers downloaded always in English

### ISSUE THREAD

**Issue by memnos** [RandomNinjaAtk/docker-radarr-extended#9]
Hello,
even if in TMDB i have trailers in Italian when running radarr-extended trailers are downloaded in English.
When i used AMTD trailers were in italians.

Is there something wrong in my config or is it a bug?

docker run -d
--name=radarr-extended
-v /opt/radarr-extended/config:/config
-v /media/Movies:/media/Movies
-p 7878:7878
-e PUID=0
-e PGID=0
-e enableAutoConfig=true
-e enableRecyclarr=true
-e enableQueueCleaner=true
-e enableExtras=true
-e extrasType=trailers
-e extrasLanguages=it
-e extrasOfficialOnly=false
-e extrasSingle=true
-e extrasKodiCompatibility=false
-e AUTOSTART=true
--restart unless-stopped
randomninjaatk/radarr-extended:latest

**Comment by RandomNinjaAtk** [comment]
Single trailer does not use the language function, it only gets the trailer that Radarr has linked. Which is likely English…

disable extrasSingle and see if it works. I’m not sure I’ll fix for the Single trailer option because when multiple trailers exist. You cannot determine the best trailer to pull automatically, other than the one Radarr provides.

**Comment by memnos** [comment]
So, this is different from AMTD because with that i could dowload single trailers in Italian?

With this config:
  -e extrastype=trailers \
  -e subtitlelanguage=it \
  -e USEFOLDERS=false \
  -e EndClient=emby \
  -e SINGLETRAILER=true \
  -e PREFER_EXISTING=true \
  -e FilePermissions=644 \
  -e FolderPermissions=755 \

**Comment by RandomNinjaAtk** [comment]
This is a completely new script, similar end goal, but not a copy/paste. So they are not the same.

**Comment by memnos** [comment]
For example Thor Love and Thunder or Top Gun Maverick

**Comment by RandomNinjaAtk** [comment]
Test that the languages work when having multiple trailers/extras. Cause honestly, I have not tested it because I don’t have a need for it and it would be a good data point to have.

**Comment by memnos** [comment]
I'll try and let you know

**Comment by RandomNinjaAtk** [comment]
I think I will fix it so it works with single trailer option, just need to think snout how I’ll implement it

**Comment by RandomNinjaAtk** [comment]
I think the latest script fixes all of the language issues... give it a whirl...

**Comment by memnos** [comment]
Should i try with
extrasSingle=true
?

**Comment by RandomNinjaAtk** [comment]
Should work with either, but not a bad idea to test both, because I can only do so much testing...

**Comment by memnos** [comment]
In the log i found this:

2022-09-09 13:14:30 :: MovieExtras :: Thor: Love and Thunder :: Searching for "it" extras...
2022-09-09 13:14:30 :: MovieExtras :: Thor: Love and Thunder :: 1 Extras Found!
2022-09-09 13:14:30 :: MovieExtras :: Thor: Love and Thunder :: 1 of 1 :: Trailer :: Single Trailer Enabled...
2022-09-09 13:14:31 :: MovieExtras :: Thor: Love and Thunder :: 1 of 1 :: Trailer :: Trailer Ufficiale (5mKjfZHDn_M) :: Downloading...
Manual processor started.
Python 64-bit 3.9.13 (main, Jul 26 2022, 13:12:30) 
[GCC 10.3.1 20211027].
Guessit version: 3.4.3.
/usr/bin/python3
Loading config file /sma.ini.
Force-convert is true, so process-same-extensions is being overridden to true as well
No-tagging enabled
2022-09-09 13:14:38 :: MovieExtras :: Thor: Love and Thunder :: 1 of 1 :: Trailer :: Trailer Ufficiale (5mKjfZHDn_M) :: Compete
/config/extended/scripts/MovieExtras.bash: line 193: /dev/null: Permission denied
2022-09-09 13:14:38 :: MovieExtras :: Thor: Love and Thunder :: 1 of 1 :: Trailer :: Trailer Ufficiale :: ERROR :: SMA Processing Error
2022-09-09 13:14:38 :: MovieExtras :: Thor: Love and Thunder :: 1 of 1 :: Trailer :: Trailer Ufficiale :: INFO: deleted: /media//Movies/Thor Love and Thunder (2022)/movie-trailer.mkv
2022-09-09 13:14:38 :: MovieExtras :: Thor: Love and Thunder :: 1 of 1 :: Trailer :: Finished processing single trailer download


Why this:
/config/extended/scripts/MovieExtras.bash: line 193: /dev/null: Permission denied


I see no trailer in the folder after this

**Comment by RandomNinjaAtk** [comment]
Try the latest update

**Comment by memnos** [comment]
> Also make sure you update your language code per the parameters in the readme or it won't likely work... Your sample log output shows your using an incorrect language code....

Sorry, can you please tell me how to do this?

**Comment by memnos** [comment]
Do you mean this?

  -e extrasLanguages=it-IT,en-US

**Comment by RandomNinjaAtk** [comment]
Yes, change it to what you want though.

**Comment by memnos** [comment]
With these settings Italian trailer has beenn downloaded.

  -e enableExtras=true \
  -e extrasType=trailers \
  -e extrasLanguages=it-IT,en-US \
  -e extrasOfficialOnly=false \
  -e extrasSingle=true \
  -e extrasKodiCompatibility=true \
